# Generated by Django 3.0.5 on 2023-09-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SBI', 'SBI'), ('UNION_BANK_OF_INDIA', 'UNION_BANK_OF_INDIA'), ('ICIC', 'ICIC')], max_length=128)),
                ('ifsc_code', models.CharField(max_length=128)),
                ('branch', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=6)),
                ('made_at', models.DateTimeField(auto_now_add=True)),
                ('from_account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_account_id', to='banking.Account')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_id', to='banking.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('SUPERVISOR', 'Supervisor')], max_length=20)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='banking.Bank')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='banking.Bank'),
        ),
    ]
