# Generated by Django 3.0.5 on 2023-09-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20230909_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='mobile_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
