# Generated by Django 3.0.5 on 2023-09-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20230911_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='bank_id',
            new_name='bank',
        ),
    ]
