# Generated by Django 3.0.5 on 2023-09-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_auto_20230911_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='bank_id',
            new_name='bank',
        ),
    ]
