# Generated by Django 3.0.5 on 2023-09-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_auto_20230912_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='to_account_id',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_account_id',
        ),
    ]
