# Generated by Django 3.0.5 on 2023-09-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_auto_20230912_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
