# Generated by Django 3.0.5 on 2023-09-12 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('from_account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_account_id', to='banking.Account')),
                ('to_account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_account_id', to='banking.Account')),
            ],
        ),
    ]
