# Generated by Django 3.0.5 on 2023-09-15 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_id', to='banking.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_account_id', to='banking.Account'),
        ),
    ]
